"use client";

import { useEffect } from "react";
import { translations } from "@/lib/i18n";

export default function SettingsModal({
  isOpen,
  onClose,
  limitOnePerDay,
  onToggleLimitOnePerDay,
  enablePriorityDonation = true,
  onToggleEnablePriorityDonation,
  donationLink = "",
  onChangeDonationLink,
  minPriorityDonation = 10000,
  onChangeMinPriorityDonation,
  lang = "id",
}) {
  const t = translations[lang] || translations.id;
  const sText = t.settingsModal || {
    title: lang === "en" ? "Settings" : "Pengaturan",
    subtitle:
      lang === "en"
        ? "Manage your live stream configuration and queue rules"
        : "Kelola konfigurasi dan aturan antrean live stream Anda",
    sectionLiveQueue: lang === "en" ? "Live Queue Rules" : "Aturan Antrean Live",
    limitDailyTitle:
      lang === "en"
        ? "Limit to only 1 Request per day?"
        : "Batasi hanya 1 kali Request perhari?",
    limitDailyDesc:
      lang === "en"
        ? "If enabled, the live room link generated by the system will restrict each viewer to submit only 1 request per day. If disabled, viewers can submit requests multiple times."
        : "Jika diaktifkan, link room live yang digenerate sistem akan mencatat setiap penonton agar hanya bisa merequest 1 kali saja per hari. Jika tidak, penonton dapat merequest lagi tanpa batas.",
    statusActive: lang === "en" ? "Active (Max 1x / Day)" : "Aktif (Maks 1x / Hari)",
    statusDisabled: lang === "en" ? "Disabled (Unlimited)" : "Nonaktif (Bebas Request)",
    tipNote:
      lang === "en"
        ? "This setting immediately syncs to the public live room links shared with your viewers."
        : "Pengaturan ini langsung tersinkronisasi ke tautan room live publik yang Anda bagikan ke penonton.",
    btnClose: lang === "en" ? "Done" : "Selesai",
  };

  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = "hidden";
      return () => {
        document.body.style.overflow = "";
      };
    }
  }, [isOpen]);

  useEffect(() => {
    const handleKey = (e) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [onClose]);

  if (!isOpen) return null;

  return (
    <div
      className="modal-overlay active"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
      style={{ zIndex: 1250 }}
    >
      <div
        className="modal settings-modal"
        onClick={(e) => e.stopPropagation()}
        style={{
          maxWidth: "560px",
          width: "92vw",
          padding: "24px 26px",
          position: "relative",
          maxHeight: "90vh",
          overflowY: "auto",
          boxShadow: "var(--shadow-lg), 0 20px 45px -15px rgba(0, 0, 0, 0.25)",
        }}
      >
        {/* Modal Header */}
        <div
          style={{
            display: "flex",
            alignItems: "flex-start",
            justifyContent: "space-between",
            marginBottom: "20px",
            borderBottom: "1px solid var(--border-color)",
            paddingBottom: "16px",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
            <div
              style={{
                width: "42px",
                height: "42px",
                borderRadius: "12px",
                background: "var(--accent-subtle)",
                color: "var(--accent-primary)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                flexShrink: 0,
              }}
            >
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="3" />
                <path d="M19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 010 2.83 2 2 0 01-2.83 0l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-2 2 2 2 0 01-2-2v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83 0 2 2 0 010-2.83l.06-.06a1.65 1.65 0 00.33-1.82 1.65 1.65 0 00-1.51-1H3a2 2 0 01-2-2 2 2 0 012-2h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 010-2.83 2 2 0 012.83 0l.06.06a1.65 1.65 0 001.82.33H9a1.65 1.65 0 001-1.51V3a2 2 0 012-2 2 2 0 012 2v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 0 2 2 0 010 2.83l-.06.06a1.65 1.65 0 00-.33 1.82V9a1.65 1.65 0 001.51 1H21a2 2 0 012 2 2 2 0 01-2 2h-.09a1.65 1.65 0 00-1.51 1z" />
              </svg>
            </div>
            <div>
              <h2
                style={{
                  fontSize: "1.18rem",
                  fontWeight: 700,
                  color: "var(--text-primary)",
                  margin: 0,
                  lineHeight: "1.25",
                }}
              >
                {sText.title}
              </h2>
              <p
                style={{
                  fontSize: "0.82rem",
                  color: "var(--text-secondary)",
                  margin: "3px 0 0 0",
                  lineHeight: "1.35",
                }}
              >
                {sText.subtitle}
              </p>
            </div>
          </div>

          <button
            type="button"
            className="modal-close"
            onClick={onClose}
            aria-label="Close settings"
            style={{
              background: "none",
              border: "none",
              color: "var(--text-tertiary)",
              cursor: "pointer",
              padding: "6px",
              borderRadius: "var(--radius-sm)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              transition: "var(--transition-fast)",
            }}
          >
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>

        {/* ══ SECTION 1: ATURAN ANTREAN LIVE (1x PER HARI) ══ */}
        <div style={{ marginBottom: "12px" }}>
          <span
            style={{
              fontSize: "0.72rem",
              fontWeight: 700,
              textTransform: "uppercase",
              letterSpacing: "0.06em",
              color: "var(--accent-primary)",
            }}
          >
            {sText.sectionLiveQueue}
          </span>
        </div>

        {/* Setting Card 1 */}
        <div
          style={{
            background: "var(--bg-secondary)",
            border: "1px solid var(--border-color)",
            borderRadius: "var(--radius-md)",
            padding: "16px 18px",
            marginBottom: "20px",
            transition: "all var(--transition-normal)",
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "flex-start",
              justifyContent: "space-between",
              gap: "16px",
            }}
          >
            <div style={{ flex: 1, minWidth: 0 }}>
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "8px",
                  marginBottom: "6px",
                  flexWrap: "wrap",
                }}
              >
                <span
                  style={{
                    fontSize: "0.95rem",
                    fontWeight: 700,
                    color: "var(--text-primary)",
                  }}
                >
                  {sText.limitDailyTitle}
                </span>

                <span
                  style={{
                    fontSize: "0.7rem",
                    fontWeight: 600,
                    padding: "2px 8px",
                    borderRadius: "9999px",
                    background: limitOnePerDay ? "rgba(34, 197, 94, 0.15)" : "rgba(148, 163, 184, 0.15)",
                    color: limitOnePerDay ? "#22c55e" : "var(--text-tertiary)",
                    border: limitOnePerDay
                      ? "1px solid rgba(34, 197, 94, 0.3)"
                      : "1px solid var(--border-color)",
                    transition: "all 0.2s ease",
                  }}
                >
                  {limitOnePerDay ? sText.statusActive : sText.statusDisabled}
                </span>
              </div>

              <p
                style={{
                  fontSize: "0.82rem",
                  color: "var(--text-secondary)",
                  lineHeight: "1.5",
                  margin: 0,
                }}
              >
                {sText.limitDailyDesc}
              </p>
            </div>

            {/* Toggle Switch */}
            <button
              type="button"
              className={`btn-toggle-switch ${limitOnePerDay ? "active" : ""}`}
              onClick={() => onToggleLimitOnePerDay?.(!limitOnePerDay)}
              role="switch"
              aria-checked={limitOnePerDay}
              aria-label={sText.limitDailyTitle}
              style={{ marginTop: "4px" }}
            >
              <span className="toggle-switch-thumb"></span>
            </button>
          </div>
        </div>

        {/* ══ SECTION 2: PRIORITAS DONASI (FAST-TRACK / VIP) ══ */}
        <div style={{ marginBottom: "12px" }}>
          <span
            style={{
              fontSize: "0.72rem",
              fontWeight: 700,
              textTransform: "uppercase",
              letterSpacing: "0.06em",
              color: "#f59e0b",
            }}
          >
            {lang === "en" ? "Priority Donation System (Fast-Track)" : "Sistem Prioritas Donasi (Fast-Track / VIP)"}
          </span>
        </div>

        {/* Setting Card 2: Donation Priority Toggle & Link */}
        <div
          style={{
            background: "var(--bg-secondary)",
            border: "1px solid var(--border-color)",
            borderRadius: "var(--radius-md)",
            padding: "16px 18px",
            marginBottom: "20px",
          }}
        >
          {/* Toggle Priority System */}
          <div
            style={{
              display: "flex",
              alignItems: "flex-start",
              justifyContent: "space-between",
              gap: "16px",
              marginBottom: "16px",
              paddingBottom: "14px",
              borderBottom: "1px solid var(--border-color)",
            }}
          >
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "4px" }}>
                <span style={{ fontSize: "0.95rem", fontWeight: 700, color: "var(--text-primary)" }}>
                  {lang === "en" ? "Auto-Prioritize Donated Requests?" : "Auto-Prioritas Donasi ke Urutan Teratas?"}
                </span>
                <span
                  style={{
                    fontSize: "0.7rem",
                    fontWeight: 600,
                    padding: "2px 8px",
                    borderRadius: "9999px",
                    background: enablePriorityDonation ? "rgba(245, 158, 11, 0.15)" : "rgba(148, 163, 184, 0.15)",
                    color: enablePriorityDonation ? "#f59e0b" : "var(--text-tertiary)",
                    border: enablePriorityDonation ? "1px solid rgba(245, 158, 11, 0.3)" : "1px solid var(--border-color)",
                  }}
                >
                  {enablePriorityDonation
                    ? (lang === "en" ? "Active (Sorted by Donation)" : "Aktif (Prioritas Donasi Terbesar)")
                    : (lang === "en" ? "Disabled" : "Nonaktif")}
                </span>
              </div>
              <p style={{ fontSize: "0.82rem", color: "var(--text-secondary)", lineHeight: "1.45", margin: 0 }}>
                {lang === "en"
                  ? "When enabled, requests with verified/claimed donations automatically jump to the top of the queue according to their donation amount (Super VIP 50k > VIP 25k > Fast-Track 10k)."
                  : "Jika diaktifkan, antrean otomatis mengurutkan website yang mendonasi ke posisi teratas sesuai nominalnya (Super VIP 50k > VIP 25k > Fast-Track 10k > Reguler)."}
              </p>
            </div>
            <button
              type="button"
              className={`btn-toggle-switch ${enablePriorityDonation ? "active" : ""}`}
              onClick={() => onToggleEnablePriorityDonation?.(!enablePriorityDonation)}
              role="switch"
              aria-checked={enablePriorityDonation}
              style={{ marginTop: "4px" }}
            >
              <span className="toggle-switch-thumb"></span>
            </button>
          </div>

          {/* Donation Link Input */}
          <div style={{ marginBottom: "14px" }}>
            <label style={{ display: "block", fontSize: "0.82rem", fontWeight: 600, color: "var(--text-primary)", marginBottom: "6px" }}>
              {lang === "en" ? "Host Donation Link (Saweria / Trakteer / Sociabuzz / QRIS)" : "Link Donasi Host (Saweria / Trakteer / Sociabuzz / QRIS)"}
            </label>
            <div style={{ position: "relative" }}>
              <input
                type="url"
                value={donationLink}
                onChange={(e) => onChangeDonationLink?.(e.target.value)}
                placeholder="https://saweria.co/username_anda"
                className="input"
                style={{ width: "100%", paddingLeft: "38px", height: "42px", fontSize: "0.88rem" }}
              />
              <span
                style={{
                  position: "absolute",
                  left: "12px",
                  top: "50%",
                  transform: "translateY(-50%)",
                  color: "var(--text-tertiary)",
                  display: "flex",
                  alignItems: "center",
                }}
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71" />
                  <path d="M14 11a5 5 0 00-7.54-.54l-3 3a5 5 0 007.07 7.07l1.71-1.71" />
                </svg>
              </span>
            </div>
            <span style={{ display: "block", fontSize: "0.74rem", color: "var(--text-tertiary)", marginTop: "4px" }}>
              {lang === "en"
                ? "This link will be displayed to your viewers in the room so they can easily donate to prioritize their website."
                : "Tautan ini akan ditampilkan di form room agar penonton bisa langsung mengklik dan berdonasi ke Saweria/Trakteer Anda."}
            </span>
          </div>

          {/* Minimum Priority Donation */}
          <div>
            <label style={{ display: "block", fontSize: "0.82rem", fontWeight: 600, color: "var(--text-primary)", marginBottom: "6px" }}>
              {lang === "en" ? "Minimum Donation for Fast-Track (Rp)" : "Minimal Donasi untuk Prioritas Fast-Track (Rp)"}
            </label>
            <input
              type="number"
              min="1000"
              step="1000"
              value={minPriorityDonation}
              onChange={(e) => onChangeMinPriorityDonation?.(parseInt(e.target.value, 10) || 10000)}
              className="input"
              style={{ width: "100%", maxWidth: "220px", height: "40px", fontSize: "0.88rem", paddingLeft: "14px" }}
            />
          </div>
        </div>

        {/* Tip Box */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "10px",
            background: "rgba(56, 189, 248, 0.08)",
            border: "1px solid rgba(56, 189, 248, 0.2)",
            borderRadius: "var(--radius-sm)",
            padding: "10px 14px",
            marginBottom: "22px",
            fontSize: "0.78rem",
            color: "var(--text-secondary)",
            lineHeight: "1.4",
          }}
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="var(--accent-primary)"
            strokeWidth="2"
            style={{ flexShrink: 0 }}
          >
            <circle cx="12" cy="12" r="10" />
            <line x1="12" y1="16" x2="12" y2="12" />
            <line x1="12" y1="8" x2="12.01" y2="8" />
          </svg>
          <span>{sText.tipNote}</span>
        </div>

        {/* Action Button */}
        <div style={{ display: "flex", justifyContent: "flex-end" }}>
          <button
            type="button"
            className="btn btn-primary"
            onClick={onClose}
            style={{ minWidth: "100px", padding: "9px 20px" }}
          >
            {sText.btnClose}
          </button>
        </div>
      </div>
    </div>
  );
}
